<html>
<head>
  <meta charset="utf-8">
  <title>Famoso</title>
</head>
<body>
  <?php
  //variable de tipo cadena
  $nombre="Messi";
  //variable de tipo integer
  $edad=32;
  //variable de tipo booleano
  $estavivo=true;
  //Muestra por pantalla todas las variables dentro de etiquetas p
echo "<p>Se llama ".$nombre;
echo "<p>Tiene ".$edad." años";
echo "<p>Está vivo".$estavivo;
  ?>
</body>
</html>
